name: compile-builder
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base ^>= 4.15

executables:
  compile-builder:
    source-dirs: app
    main: Main.hs
    dependencies:
      - process ^>= 1.6
      - filepath ^>= 1.4
      - directory ^>= 1.3
