name: hsnixpkgs-stdenv-pack
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - bytestring ^>= 0.10
  - filepath ^>= 1.4
  - directory ^>= 1.3

library:
  source-dirs: src
  dependencies:
    - mtl ^>= 2.2
    - hashable ^>= 1.3
    - unordered-containers ^>= 0.2
    - cryptonite ^>= 0.29
    - aeson ^>= 2.0
    - nix-archive
    - lzma ^>= 0.0
    - binary ^>= 0.8

executables:
  pack-stdenv-linux:
    main: Main.hs
    source-dirs: app/linux
    dependencies:
      - hsnixpkgs-stdenv-pack
      - yaml ^>= 0.11
    when:
      - condition: os(linux)
        then:
          buildable: true
        else:
          buildable: false
