name: hsnixpkgs-stdenv-unpack
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - bytestring ^>= 0.10

library:
  source-dirs: src
  include-dirs:
    - include
  c-sources:
    - cbits/rewrite.c
  cc-options:
    - -O3

executables:
  unpack-stdenv-linux:
    main: Main.hs
    source-dirs: app/linux
    dependencies:
      - hsnixpkgs-stdenv-unpack
      - nix-archive
      - lzma ^>= 0.0
      - binary ^>= 0.8
    when:
      - condition: os(linux)
        then:
          buildable: true
        else:
          buildable: false
