name: hsnixpkgs
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

extra-source-files:
  - stdenv/**/**/*

ghc-options:
  - -fenable-th-splice-warnings
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - bytestring ^>= 0.10
  - data-default ^>= 0.7
  - hsnix-core

library:
  source-dirs: src
  dependencies:
    - template-haskell ^>= 2.17
    - mtl ^>= 2.2
    - containers ^>= 0.6
    - hashable ^>= 1.3
    - unordered-containers ^>= 0.2
    - filepath ^>= 1.4
    - directory ^>= 1.3
    - singletons ^>= 3.0
    - singletons-base ^>= 3.0
    - hsnixpkgs-boot-builderlib
    - yaml ^>= 0.11
    - hsnixpkgs-stdenv-pack
  default-extensions:
    - ApplicativeDo
    - DataKinds
    - KindSignatures
    - ScopedTypeVariables
    - StandaloneDeriving
    - TypeApplications
  other-modules:
    - HsNixPkgs.HsBuilder.Internal.BuildMod
    - HsNixPkgs.HsBuilder.Internal.BuildMod.TH
    - HsNixPkgs.HsBuilder.Internal.BuildMod.Types
